apiVersion: v2
name: cdc-system
description: A professional CDC system with Kafka, Debezium, and monitoring
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: kafka
    version: 21.4.4
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: elasticsearch
    version: 19.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  - name: prometheus
    version: 45.7.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 6.50.7
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled